ersion: '3.9'

services:

    jupyter:
        build: .
        image: galai-test
        ports:
            - 8888:8888
        volumes:
            - ./notebooks:/notebooks
        command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                    device_ids: ['0']
                    capabilities: [gpu]